/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminQuestsRouteImport } from './routes/admin/quests'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoreRouteImport } from './routes/admin/lore'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCharacterRouteImport } from './routes/admin/character'
import { Route as PublicSandboxRouteImport } from './routes/_public/sandbox'
import { Route as PublicQuestsRouteImport } from './routes/_public/quests'
import { Route as PublicLoreRouteImport } from './routes/_public/lore'
import { Route as PublicInventoryRouteImport } from './routes/_public/inventory'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicQuestsSlugRouteImport } from './routes/_public/quests_.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestsRoute = AdminQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoreRoute = AdminLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharacterRoute = AdminCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AdminRoute,
} as any)
const PublicSandboxRoute = PublicSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuestsRoute = PublicQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoreRoute = PublicLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInventoryRoute = PublicInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuestsSlugRoute = PublicQuestsSlugRouteImport.update({
  id: '/quests_/$slug',
  path: '/quests/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/inventory': typeof PublicInventoryRoute
  '/lore': typeof PublicLoreRoute
  '/quests': typeof PublicQuestsRoute
  '/sandbox': typeof PublicSandboxRoute
  '/admin/character': typeof AdminCharacterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lore': typeof AdminLoreRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/': typeof AdminIndexRoute
  '/quests/$slug': typeof PublicQuestsSlugRoute
}
export interface FileRoutesByTo {
  '/contact': typeof PublicContactRoute
  '/inventory': typeof PublicInventoryRoute
  '/lore': typeof PublicLoreRoute
  '/quests': typeof PublicQuestsRoute
  '/sandbox': typeof PublicSandboxRoute
  '/admin/character': typeof AdminCharacterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lore': typeof AdminLoreRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/quests/$slug': typeof PublicQuestsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/inventory': typeof PublicInventoryRoute
  '/_public/lore': typeof PublicLoreRoute
  '/_public/quests': typeof PublicQuestsRoute
  '/_public/sandbox': typeof PublicSandboxRoute
  '/admin/character': typeof AdminCharacterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lore': typeof AdminLoreRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/quests_/$slug': typeof PublicQuestsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/inventory'
    | '/lore'
    | '/quests'
    | '/sandbox'
    | '/admin/character'
    | '/admin/login'
    | '/admin/lore'
    | '/admin/messages'
    | '/admin/quests'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/'
    | '/quests/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/inventory'
    | '/lore'
    | '/quests'
    | '/sandbox'
    | '/admin/character'
    | '/admin/login'
    | '/admin/lore'
    | '/admin/messages'
    | '/admin/quests'
    | '/admin/settings'
    | '/admin/skills'
    | '/'
    | '/admin'
    | '/quests/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/contact'
    | '/_public/inventory'
    | '/_public/lore'
    | '/_public/quests'
    | '/_public/sandbox'
    | '/admin/character'
    | '/admin/login'
    | '/admin/lore'
    | '/admin/messages'
    | '/admin/quests'
    | '/admin/settings'
    | '/admin/skills'
    | '/_public/'
    | '/admin/'
    | '/_public/quests_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quests': {
      id: '/admin/quests'
      path: '/quests'
      fullPath: '/admin/quests'
      preLoaderRoute: typeof AdminQuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lore': {
      id: '/admin/lore'
      path: '/lore'
      fullPath: '/admin/lore'
      preLoaderRoute: typeof AdminLoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/character': {
      id: '/admin/character'
      path: '/character'
      fullPath: '/admin/character'
      preLoaderRoute: typeof AdminCharacterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/sandbox': {
      id: '/_public/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof PublicSandboxRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quests': {
      id: '/_public/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof PublicQuestsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/lore': {
      id: '/_public/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof PublicLoreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/inventory': {
      id: '/_public/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof PublicInventoryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quests_/$slug': {
      id: '/_public/quests_/$slug'
      path: '/quests/$slug'
      fullPath: '/quests/$slug'
      preLoaderRoute: typeof PublicQuestsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicInventoryRoute: typeof PublicInventoryRoute
  PublicLoreRoute: typeof PublicLoreRoute
  PublicQuestsRoute: typeof PublicQuestsRoute
  PublicSandboxRoute: typeof PublicSandboxRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicQuestsSlugRoute: typeof PublicQuestsSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicInventoryRoute: PublicInventoryRoute,
  PublicLoreRoute: PublicLoreRoute,
  PublicQuestsRoute: PublicQuestsRoute,
  PublicSandboxRoute: PublicSandboxRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicQuestsSlugRoute: PublicQuestsSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminCharacterRoute: typeof AdminCharacterRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoreRoute: typeof AdminLoreRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminQuestsRoute: typeof AdminQuestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCharacterRoute: AdminCharacterRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoreRoute: AdminLoreRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminQuestsRoute: AdminQuestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
